version: '3.7'

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - F5_USERNAME=${F5_USERNAME}
      - F5_PASSWORD=${F5_PASSWORD}
    networks:
      - ansible-net

networks:
  ansible-net:
      driver: bridge