- name: Manage Enforcement Mode
  hosts: webservers
  gather_facts: false
  collections:
    - f5devcentral.cloudservices
  connection: httpapi

  vars:
    ansible_network_os: f5devcentral.cloudservices.f5
    ansible_host: "api.cloudservices.f5.com"
    ansible_user: "user@example.com"
    ansible_httpapi_password: "password"
    ansible_httpapi_use_ssl: yes
    subscription_id: "s-xxxxxxxxxx"

  tasks:
    - name: Update EAP Protection mode
      f5_cs_eap_protection_mode:
        subscription_id: "{{ subscription_id }}"
        hi_risk_attack:
          enabled: true
          enforcement_mode: "monitoring"
        threat_campaign:
          enabled: true
          enforcement_mode: "monitoring"
        malicious_ip:
          enabled: true
          enforcement_mode: "monitoring"
