- name: Manage EAP Application
  hosts: webservers
  gather_facts: false
  collections:
    - f5devcentral.cloudservices
  connection: httpapi

  vars:
    ansible_network_os: f5devcentral.cloudservices.f5
    ansible_host: "api.cloudservices.f5.com"
    ansible_user: "user@example.com"
    ansible_httpapi_password: "password"
    ansible_httpapi_use_ssl: yes
    fqdn: "fqdn.demo.net"
    instance_ip: "127.0.0.1"
    subscription_id: "s-xxxxxxxx"

  tasks:
    - name: Read All EAP apps
      f5_cs_eap_subscription_app:
        state: "fetch"

    - name: Create EAP instance
      f5_cs_eap_subscription_app:
        service_instance_name: "{{ fqdn }}"

    - name: Create EAP instance
      f5_cs_eap_subscription_app:
        service_instance_name: "my_app"
        fqdn: "{{ fqdn }}"

    - name: create eap for selected region
      f5_cs_eap_subscription_app:
        waf_regions:
          aws:
            - name: "eu-west-3"
              value:
                endpoint:
                  http:
                    enabled: true
                    port: 80
                  ips:
                    - "{{ instance_ip }}"
        service_instance_name: "{{ fqdn }}"

    - name: Fetch EAP instance
      f5_cs_eap_subscription_app:
        subscription_id: "{{ subscription_id }}"
        state: "fetch"

    - name: Partial EAP instance update
      f5_cs_eap_subscription_app:
        subscription_id: "{{ subscription_id }}"
        wait_status_change: false
        patch: true
        configuration:
          update_comment: "update EAP subscription"
          waf_service:
            policy:
              compliance_enforcement:
                enabled: true
                data_guard:
                  enabled: true

    - name: Partial EAP instance update with waf regions
      f5_cs_eap_subscription_app:
        subscription_id: "{{ subscription_id }}"
        patch: true
        wait_status_change: false
        waf_regions:
          aws:
            - name: "us-west-1"
              value:
                endpoint:
                  http:
                    enabled: true
                    port: 80
                  ips:
                    - "{{ instance_ip }}"
        configuration:
          update_comment: "update EAP subscription"
          waf_service:
            policy:
              compliance_enforcement:
                enabled: true
                data_guard:
                  enabled: true

    - name: Full EAP instance update
      f5_cs_eap_subscription_app:
        subscription_id: "{{ subscription_id }}"
        service_instance_name: "{{ fqdn }}"
        configuration:
          update_comment: "update EAP subscription"
          waf_service:
            application:
              description: "eap subscription"
              fqdn: "{{ fqdn }}"
              http:
                enabled: true
                port: 80
              https:
                enabled: false
                port: 443
                tls:
                  certificate_id: ""
              waf_regions:
                aws:
                  "us-east-1":
                    endpoint:
                      http:
                        enabled: true
                        port: 80
                      ips:
                        - "{{ instance_ip }}"
            policy:
              encoding: "utf-8"
              compliance_enforcement:
                enabled: true
                data_guard:
                  enabled: true
                sensitive_parameters:
                  enabled: false
              high_risk_attack_mitigation:
                enabled: false
                enforcement_mode: "monitoring"
                allowed_methods:
                  enabled: false
                api_compliance_enforcement:
                  enabled: false
                disallowed_file_types:
                  enabled: false
                  file_types:
                    - "dll"
                geolocation_enforcement:
                  enabled: true
                  disallowed_country_codes:
                    - AD
                http_compliance_enforcement:
                  enabled: false
                ip_enforcement:
                  enabled: true
                  ips:
                    - address: "192.168.1.1"
                      description: "spam"
                      action: "block"
                      log: true
                signature_enforcement:
                  enabled: false
              malicious_ip_enforcement:
                enabled: false
                enforcement_mode: "monitoring"
                ip_categories:
                  - block: true
                    log: true
                    name: "mobile_threats"
              threat_campaigns:
                enabled: true
                enforcement_mode: "monitoring"
                campaigns: []

    - name: Suspend EAP instance
      f5_cs_eap_subscription_app:
        subscription_id: "{{ subscription_id }}"
        state: "suspended"

    - name: Activate EAP instance
      f5_cs_eap_subscription_app:
        subscription_id: "{{ subscription_id }}"
        state: "active"

    - name: Remove EAP instance
      f5_cs_eap_subscription_app:
        subscription_id: "{{ subscription_id }}"
        state: "absent"