- name: Apply SSL certificate
  hosts: webservers
  gather_facts: false
  collections:
    - f5devcentral.cloudservices
  connection: httpapi

  vars:
    ansible_network_os: f5devcentral.cloudservices.f5
    ansible_host: "api.cloudservices.f5.com"
    ansible_user: "user@example.com"
    ansible_httpapi_password: "password"
    ansible_httpapi_use_ssl: yes

  tasks:
    - name: Apply SSL Certificate
      f5_cs_eap_certificate:
        subscription_id: "s-xxxxxxxxxx"
        certificate: "{{ lookup('file', './fqdn.cert') }}"
        private_key: "{{ lookup('file', './fqdn.key') }}"
        passphrase: "demo_ansible"
        certificate_chain: "{{ lookup('file', './chain.cert') }}"
        https_port: 443
        https_redirect: true
        update_comment: "update SSL certificate"
