- name: Manage Enforcement Rules
  hosts: webservers
  gather_facts: false
  collections:
    - f5devcentral.cloudservices
  connection: httpapi

  vars:
    ansible_network_os: f5devcentral.cloudservices.f5
    ansible_host: "api.cloudservices.f5.com"
    ansible_user: "user@example.com"
    ansible_httpapi_password: "password"
    ansible_httpapi_use_ssl: yes
    subscription_id: "s-xxxxxxxxxx"

  tasks:
    - name: Update IP Enforcement Rules
      f5_cs_eap_ip_enforcement:
        subscription_id: "{{ subscription_id }}"
        ip_enforcement:
          - address: "192.168.1.1"
            description: "ip_1"
            action: "block"
            log: true
          - address: "192.168.1.2"
            action: "allow"
          - address: "192.168.1.3"
            log: false

    - name: Append IPs to the Rules
      f5_cs_eap_ip_enforcement:
        subscription_id: "{{ subscription_id }}"
        append: true
        ip_enforcement:
          - address: "192.168.1.1"
            description: "ip_1"
            action: "block"
            log: true
          - address: "192.168.1.2"
            action: "allow"
          - address: "192.168.1.3"
            log: false

    - name: Exclude IPs from the Rules
      f5_cs_eap_ip_enforcement:
        subscription_id: "{{ subscription_id }}"
        action: "absent"
        ip_enforcement:
          - address: "192.168.1.1"
          - address: "192.168.1.2"
